// <auto-generated />
namespace AulpagCollecte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ModifStops_pk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ModifStops_pk));
        
        string IMigrationMetadata.Id
        {
            get { return "202111010953540_ModifStops_pk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
