// <auto-generated />
namespace AulpagCollecte.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class TableFeed_info : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TableFeed_info));
        
        string IMigrationMetadata.Id
        {
            get { return "202111032029454_TableFeed_info"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
